#!/bin/bash

# Hub CLI para Microsistemas (Bash version)
# Autogenerated to replace hub.py
#
# Script de Bash para gestión de aplicaciones en entornos Linux/Mac.
# Provee funcionalidad equivalente a hub.ps1 para listar y ejecutar apps.

APPS_DIR="$(cd "$(dirname "$0")" && pwd)/apps"

# Colores para la salida
GREEN='\033[0;32m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

#
# Lista todas las aplicaciones disponibles en el directorio 'apps'.
# Escanea el directorio 'apps' en busca de subdirectorios con 'app.manifest.yml'.
# Muestra ID, Nombre, Tipo y Puertos.
#
function list_apps() {
    echo -e "${CYAN}Aplicaciones en Microsistemas${NC}"
    printf "%-20s %-30s %-15s %-10s\n" "ID" "Nombre" "Tipo" "Puertos"
    echo "--------------------------------------------------------------------------------"
    
    for app_dir in "$APPS_DIR"/*; do
        if [ -f "$app_dir/app.manifest.yml" ]; then
            id=$(basename "$app_dir")
            # Parse simple de YAML usando grep/sed (mejorable con yq)
            name=$(grep "name:" "$app_dir/app.manifest.yml" | head -n 1 | sed 's/name: //;s/"//g;s/'\''//g')
            type=$(grep "type:" "$app_dir/app.manifest.yml" | head -n 1 | sed 's/type: //;s/"//g;s/'\''//g')
            ports=$(grep -A 5 "ports:" "$app_dir/app.manifest.yml" | grep -v "ports:" | grep "-" | sed 's/- //;s/ //g' | tr '\n' ',' | sed 's/,$//')
            
            printf "%-20s %-30s %-15s %-10s\n" "$id" "$name" "$type" "$ports"
        fi
    done
}

#
# Ejecuta el comando de inicio ('run_cmd') de una aplicación dado su ID.
# Lee el manifiesto para encontrar el comando y lo ejecuta en el directorio de la app.
#
function run_app() {
    local app_id=$1
    if [ -z "$app_id" ]; then
        echo -e "${RED}Error:${NC} Debes especificar un ID de aplicación."
        return 1
    fi

    local app_path="$APPS_DIR/$app_id"
    local manifest="$app_path/app.manifest.yml"

    if [ ! -f "$manifest" ]; then
        echo -e "${RED}Error:${NC} Aplicación '$app_id' no encontrada o sin manifiesto."
        return 1
    fi

    # Extraer run_cmd
    local run_cmd=$(grep "run_cmd:" "$manifest" | sed 's/run_cmd: //;s/"//g;s/'\''//g')
    local type=$(grep "type:" "$manifest" | head -n 1 | sed 's/type: //;s/"//g;s/'\''//g')

    if [ -z "$run_cmd" ]; then
        if [ "$type" == "static" ]; then
            echo -e "${YELLOW}Info:${NC} La aplicación '$app_id' es estática. Ábrela en tu navegador."
            return 0
        fi
        echo -e "${RED}Error:${NC} No se definió run_cmd para '$app_id'."
        return 1
    fi

    echo -e "${GREEN}Iniciando $app_id...${NC}"
    cd "$app_path" || return 1
    eval "$run_cmd"
}

#
# Levanta una aplicación usando Docker Compose dado su ID.
# Busca la propiedad 'compose_file' en el manifiesto y ejecuta 'docker compose up -d'.
#
function up_app() {
    local app_id=$1
    if [ -z "$app_id" ]; then
        echo -e "${RED}Error:${NC} Debes especificar un ID de aplicación."
        return 1
    fi

    local app_path="$APPS_DIR/$app_id"
    local manifest="$app_path/app.manifest.yml"

    if [ ! -f "$manifest" ]; then
        echo -e "${RED}Error:${NC} Aplicación '$app_id' no encontrada."
        return 1
    fi

    local compose_file=$(grep "compose_file:" "$manifest" | sed 's/compose_file: //;s/"//g;s/'\''//g')

    if [ -z "$compose_file" ]; then
        echo -e "${YELLOW}Aviso:${NC} '$app_id' no define un compose_file en su manifiesto."
        return 0
    fi

    echo -e "${GREEN}Levantando $app_id con Docker Compose...${NC}"
    cd "$app_path" || return 1
    docker compose -f "$compose_file" up -d
}

#
# Realiza un diagnóstico del sistema.
# Verifica herramientas (docker, git, php), archivos (.env, vendor), puertos y contenedores.
#
function doctor() {
    echo -e "${CYAN}Chequeo de salud del Hub...${NC}"

    # 1. Herramientas Base
    check_tool() {
        if $1 --version > /dev/null 2>&1; then
            echo -e "${GREEN}[OK]${NC} $2 instalado."
        else
            echo -e "${RED}[ERR]${NC} $2 no encontrado."
        fi
    }

    check_tool "docker" "Docker"
    check_tool "git" "Git"
    check_tool "php" "PHP"

    # 2. Configuración
    if [ -f ".env" ]; then
        echo -e "${GREEN}[OK]${NC} Archivo .env encontrado."
    else
        echo -e "${RED}[ERR]${NC} Archivo .env NO encontrado (copia .env.example)."
    fi

    if [ -d "vendor" ]; then
        echo -e "${GREEN}[OK]${NC} Directorio vendor encontrado."
    else
        echo -e "${RED}[ERR]${NC} Directorio vendor NO encontrado (ejecuta 'make install')."
    fi

    # 3. Puertos
    check_port() {
        # Simple netcat check (if available) or skip
        if command -v nc > /dev/null; then
            if nc -z localhost $1 2>/dev/null; then
                 echo -e "${YELLOW}[WARN]${NC} Puerto $1 parece estar en uso."
            else
                 echo -e "${GREEN}[OK]${NC} Puerto $1 libre."
            fi
        else
            echo -e "${YELLOW}[INFO]${NC} Saltando chequeo de puerto $1 (nc no instalado)."
        fi
    }
    
    check_port 8000
    check_port 8080

    # 4. Docker Containers
    if command -v docker > /dev/null; then
        echo -e "\n${CYAN}Estado de Contenedores:${NC}"
        docker ps --format "{{.Names}}: {{.Status}}" | while read line; do
            if [[ "$line" == *"healthy"* ]]; then
                 echo -e "${GREEN}  [OK] $line${NC}"
            elif [[ "$line" == *"unhealthy"* ]]; then
                 echo -e "${RED}  [ERR] $line${NC}"
            else
                 echo -e "${YELLOW}  [INFO] $line${NC}"
            fi
        done
    fi
}

case "$1" in
    list)
        list_apps
        ;;
    run)
        run_app "$2"
        ;;
    up)
        up_app "$2"
        ;;
    doctor)
        doctor
        ;;
    *)
        echo "Uso: $0 {list|run <id>|up <id>|doctor}"
        exit 1
        ;;
esac
