#!/bin/bash

# Hub CLI para Microsistemas (Bash version)
# Autogenerated to replace hub.py

APPS_DIR="$(cd "$(dirname "$0")" && pwd)/apps"

# Colores para la salida
GREEN='\033[0;32m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

function list_apps() {
    echo -e "${CYAN}Aplicaciones en Microsistemas${NC}"
    printf "%-20s %-30s %-15s %-10s\n" "ID" "Nombre" "Tipo" "Puertos"
    echo "--------------------------------------------------------------------------------"
    
    for app_dir in "$APPS_DIR"/*; do
        if [ -f "$app_dir/app.manifest.yml" ]; then
            id=$(basename "$app_dir")
            # Parse simple de YAML usando grep/sed (mejorable con yq)
            name=$(grep "name:" "$app_dir/app.manifest.yml" | head -n 1 | sed 's/name: //;s/"//g;s/'\''//g')
            type=$(grep "type:" "$app_dir/app.manifest.yml" | head -n 1 | sed 's/type: //;s/"//g;s/'\''//g')
            ports=$(grep -A 5 "ports:" "$app_dir/app.manifest.yml" | grep -v "ports:" | grep "-" | sed 's/- //;s/ //g' | tr '\n' ',' | sed 's/,$//')
            
            printf "%-20s %-30s %-15s %-10s\n" "$id" "$name" "$type" "$ports"
        fi
    done
}

function run_app() {
    local app_id=$1
    if [ -z "$app_id" ]; then
        echo -e "${RED}Error:${NC} Debes especificar un ID de aplicación."
        return 1
    fi

    local app_path="$APPS_DIR/$app_id"
    local manifest="$app_path/app.manifest.yml"

    if [ ! -f "$manifest" ]; then
        echo -e "${RED}Error:${NC} Aplicación '$app_id' no encontrada o sin manifiesto."
        return 1
    fi

    # Extraer run_cmd
    local run_cmd=$(grep "run_cmd:" "$manifest" | sed 's/run_cmd: //;s/"//g;s/'\''//g')
    local type=$(grep "type:" "$manifest" | head -n 1 | sed 's/type: //;s/"//g;s/'\''//g')

    if [ -z "$run_cmd" ]; then
        if [ "$type" == "static" ]; then
            echo -e "${YELLOW}Info:${NC} La aplicación '$app_id' es estática. Ábrela en tu navegador."
            return 0
        fi
        echo -e "${RED}Error:${NC} No se definió run_cmd para '$app_id'."
        return 1
    fi

    echo -e "${GREEN}Iniciando $app_id...${NC}"
    cd "$app_path" || return 1
    eval "$run_cmd"
}

function up_app() {
    local app_id=$1
    if [ -z "$app_id" ]; then
        echo -e "${RED}Error:${NC} Debes especificar un ID de aplicación."
        return 1
    fi

    local app_path="$APPS_DIR/$app_id"
    local manifest="$app_path/app.manifest.yml"

    if [ ! -f "$manifest" ]; then
        echo -e "${RED}Error:${NC} Aplicación '$app_id' no encontrada."
        return 1
    fi

    local compose_file=$(grep "compose_file:" "$manifest" | sed 's/compose_file: //;s/"//g;s/'\''//g')

    if [ -z "$compose_file" ]; then
        echo -e "${YELLOW}Aviso:${NC} '$app_id' no define un compose_file en su manifiesto."
        return 0
    fi

    echo -e "${GREEN}Levantando $app_id con Docker Compose...${NC}"
    cd "$app_path" || return 1
    docker compose -f "$compose_file" up -d
}

function doctor() {
    echo -e "${CYAN}Chequeo de salud del Hub...${NC}"

    if docker --version > /dev/null 2>&1; then
        echo -e "${GREEN}[OK]${NC} Docker está instalado."
    else
        echo -e "${RED}[ERR]${NC} Docker no encontrado."
    fi

    if git --version > /dev/null 2>&1; then
        echo -e "${GREEN}[OK]${NC} Git está instalado."
    else
        echo -e "${RED}[ERR]${NC} Git no encontrado."
    fi

    if php --version > /dev/null 2>&1; then
        echo -e "${GREEN}[OK]${NC} PHP está instalado."
    else
        echo -e "${RED}[ERR]${NC} PHP no encontrado."
    fi

    echo -e "\n${YELLOW}Sugerencia:${NC} Asegúrate de tener los puertos 80/443 libres si vas a usar el proxy global."
}

case "$1" in
    list)
        list_apps
        ;;
    run)
        run_app "$2"
        ;;
    up)
        up_app "$2"
        ;;
    doctor)
        doctor
        ;;
    *)
        echo "Uso: $0 {list|run <id>|up <id>|doctor}"
        exit 1
        ;;
esac
