# Hub CLI para Microsistemas (PowerShell version)
# Autogenerated to replace hub.py

$APPS_DIR = Join-Path $PSScriptRoot "apps"

function Get-Apps {
    Write-Host "Aplicaciones en Microsistemas" -ForegroundColor Cyan
    $formatString = "{0,-20} {1,-30} {2,-15} {3,-10}"
    Write-Host ($formatString -f "ID", "Nombre", "Tipo", "Puertos")
    Write-Host ("-" * 80)

    Get-ChildItem $APPS_DIR -Directory | ForEach-Object {
        $manifestPath = Join-Path $_.FullName "app.manifest.yml"
        if (Test-Path $manifestPath) {
            $id = $_.Name
            $content = Get-Content $manifestPath -Raw
            
            # Simple regex parsing for YAML (no external dependencies)
            $name = if ($content -match 'name:\s*["'']?([^"''\n\r]+)["'']?') { $Matches[1] } else { "N/A" }
            $type = if ($content -match 'type:\s*["'']?([^"''\n\r]+)["'']?') { $Matches[1] } else { "N/A" }
            
            # Ports parsing
            $ports = ""
            if ($content -match 'ports:\s*\n((\s+-\s*\d+\s*\n?)+)') {
                $portsList = $Matches[1] -split '\n' | ForEach-Object { if ($_ -match '-\s*(\d+)') { $Matches[1] } }
                $ports = $portsList -join ","
            }

            Write-Host ($formatString -f $id, $name, $type, $ports)
        }
    }
}

function Run-App {
    param([string]$appId)

    if ([string]::IsNullOrWhiteSpace($appId)) {
        Write-Host "Error: Debes especificar un ID de aplicación." -ForegroundColor Red
        return
    }

    $appPath = Join-Path $APPS_DIR $appId
    $manifestPath = Join-Path $appPath "app.manifest.yml"

    if (-not (Test-Path $manifestPath)) {
        Write-Host "Error: Aplicación '$appId' no encontrada o sin manifiesto." -ForegroundColor Red
        return
    }

    $content = Get-Content $manifestPath -Raw
    $runCmd = if ($content -match 'run_cmd:\s*["'']?([^"''\n\r]+)["'']?') { $Matches[1] } else { $null }
    $type = if ($content -match 'type:\s*["'']?([^"''\n\r]+)["'']?') { $Matches[1] } else { "N/A" }

    if (-not $runCmd) {
        if ($type -eq "static") {
            Write-Host "Info: La aplicación '$appId' es estática. Ábrela en tu navegador." -ForegroundColor Yellow
            return
        }
        Write-Host "Error: No se definió run_cmd para '$appId'." -ForegroundColor Red
        return
    }

    Write-Host "Iniciando $appId..." -ForegroundColor Green
    Set-Location $appPath
    Invoke-Expression $runCmd
}

function Up-App {
    param([string]$appId)

    if ([string]::IsNullOrWhiteSpace($appId)) {
        Write-Host "Error: Debes especificar un ID de aplicación." -ForegroundColor Red
        return
    }

    $appPath = Join-Path $APPS_DIR $appId
    $manifestPath = Join-Path $appPath "app.manifest.yml"

    if (-not (Test-Path $manifestPath)) {
        Write-Host "Error: Aplicación '$appId' no encontrada." -ForegroundColor Red
        return
    }

    $content = Get-Content $manifestPath -Raw
    $composeFile = if ($content -match 'compose_file:\s*["'']?([^"''\n\r]+)["'']?') { $Matches[1] } else { $null }

    if (-not $composeFile) {
        Write-Host "Aviso: '$appId' no define un compose_file en su manifiesto." -ForegroundColor Yellow
        return
    }

    Write-Host "Levantando $appId con Docker Compose..." -ForegroundColor Green
    Set-Location $appPath
    docker compose -f $composeFile up -d
}

function Invoke-Doctor {
    Write-Host "Chequeo de salud del Hub..." -ForegroundColor Cyan

    try {
        docker --version | Out-Null
        Write-Host "[OK] Docker está instalado." -ForegroundColor Green
    } catch {
        Write-Host "[ERR] Docker no encontrado." -ForegroundColor Red
    }

    try {
        git --version | Out-Null
        Write-Host "[OK] Git está instalado." -ForegroundColor Green
    } catch {
        Write-Host "[ERR] Git no encontrado." -ForegroundColor Red
    }

    try {
        php --version | Out-Null
        Write-Host "[OK] PHP está instalado." -ForegroundColor Green
    } catch {
        Write-Host "[ERR] PHP no encontrado." -ForegroundColor Red
    }

    Write-Host "`nSugerencia: Asegúrate de tener los puertos 80/443 libres si vas a usar el proxy global." -ForegroundColor Yellow
}

$command = $args[0]
$subArg = $args[1]

switch ($command) {
    "list" { Get-Apps }
    "run"  { Run-App $subArg }
    "up"   { Up-App $subArg }
    "doctor" { Invoke-Doctor }
    default {
        Write-Host "Uso: .\hub.ps1 {list|run <id>|up <id>|doctor}"
        exit 1
    }
}
