name: Reporte de Error
description: Crea un informe para ayudarnos a mejorar
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo para reportar un error.
  - type: textarea
    id: what-happened
    attributes:
      label: ¿Qué sucedió?
      description: Describe el error de la forma más clara posible.
      placeholder: El sistema falla al...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Pasos para reproducir
      description: Indica los pasos para encontrar el error.
      placeholder: |
        1. Ir a...
        2. Hacer click en...
        3. Ver el error...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamiento esperado
      description: ¿Qué debería haber pasado?
  - type: input
    id: version
    attributes:
      label: Versión del Micro-sistema
      description: Si aplica, indica qué app falla.
